CREATE TABLE IF NOT EXISTS T_USUARIO (
    USU_ID       BIGSERIAL  PRIMARY KEY,
    USU_LOGIN    VARCHAR(100),
    USU_NOME     VARCHAR(100),
    USU_EMAIL    VARCHAR(100),
    USU_SENHA    VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS T_UF (
   UF_ID      BIGSERIAL  PRIMARY KEY,
   UF_NOME    VARCHAR(100),
   UF_SIGLA   VARCHAR(10)  
);

CREATE TABLE IF NOT EXISTS T_CIDADE (
   CID_ID      BIGSERIAL  PRIMARY KEY,
   CID_NOME    VARCHAR(100),
   UF_ID       BIGINT NOT NULL,
   CONSTRAINT FK_CIDADE_UF 
        FOREIGN KEY (UF_ID) REFERENCES T_UF (UF_ID)
);

CREATE TABLE IF NOT EXISTS T_CLIENTE (
    CLI_ID     BIGSERIAL  PRIMARY KEY,
    CLI_CNPJ   VARCHAR(20),
    CLI_NOME   VARCHAR(100),
    CLI_DDI    VARCHAR(5), 
    CLI_DDD    VARCHAR(5),
    CLI_FONE   VARCHAR(10),
    CLI_ATIVO  VARCHAR(1) DEFAULT 'S'
);

CREATE TABLE IF NOT EXISTS T_ENDERCLI (
    END_ID         BIGSERIAL  PRIMARY KEY,
    CLI_ID         BIGINT NOT NULL,
    CID_ID         BIGINT NOT NULL, 
    CLI_BAIRRO     VARCHAR(100),
    CLI_LOGRADOURO VARCHAR(100),
    CLI_CEP        VARCHAR(10), 	
    CLI_NUMERO     INTEGER,
    CLI_ENDERECO   VARCHAR(100),
    CLI_ATIVO      VARCHAR(1) DEFAULT 'S',
    CONSTRAINT FK_ENDERCLI_CLIENTE 
        FOREIGN KEY (CLI_ID) REFERENCES T_CLIENTE (CLI_ID),
    CONSTRAINT FK_ENDERCLI_CIDADE
        FOREIGN KEY (CID_ID) REFERENCES T_CIDADE (CID_ID)
);

CREATE TABLE IF NOT EXISTS T_STATUS (
   STT_ID BIGSERIAL PRIMARY KEY, 
   STT_NOME VARCHAR(100), 
   STT_COR VARCHAR(20) 
);

CREATE TABLE IF NOT EXISTS T_ORDEM (
    ORD_ID          BIGSERIAL  PRIMARY KEY,
    CLI_ID          BIGINT NOT NULL,
    END_ID          BIGINT NOT NULL,
    STT_ID          BIGINT NOT NULL,
    ORD_OBSERVACAO  VARCHAR(500),
    ORD_DATA        DATE,
    ORD_HORA        VARCHAR(10),
    ORD_RESPONSAVEL BIGINT,
    
    CONSTRAINT FK_ORDEM_CLIENTE 
        FOREIGN KEY (CLI_ID) REFERENCES T_CLIENTE (CLI_ID),
    CONSTRAINT FK_ORDEM_ENDERCLI 
        FOREIGN KEY (END_ID) REFERENCES T_ENDERCLI (END_ID),
    CONSTRAINT FK_ORDEM_USUARIO 
        FOREIGN KEY (ORD_RESPONSAVEL) REFERENCES T_USUARIO (USU_ID),
    CONSTRAINT FK_ORDEM_STATUS
        FOREIGN KEY (STT_ID) REFERENCES T_STATUS (STT_ID)    
);
